branch-defaults:
  default:
    environment: udagram-env
    group_suffix: null
environment-defaults:
  udagram-env:
    branch: null
    repository: null
global:
  application_name: udagram
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: null
  workspace_type: Application
deploy:
  artifact: www/Archive.zip
